spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 0
  servlet:
    context-path: /onboardingkit/api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: WARN
    org.springframework: INFO
