spring:
  datasource:
    url: jdbc:h2:file:./data/demo-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MySQL   # 프로젝트 내부에 H2 DB 저장, 동시 접속 가능
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  security:
    user:
      name: admin
      password: admin1!
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - profile
              - email
  devtools:
    restart:
      enabled: true
  sql:
    init:
      mode: always
server:
  port: 8080
  servlet:
    context-path: /onboardingkit/api # todo. api 패스 공통으로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret: "mykey"