spring:
  datasource:
    url: jdbc:h2:file:C:/Users/1117mg/IdeaProjects/onboarding-kit-backend
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  devtools:
    restart:
      enabled: true